version: "3.7"

services:

  grafana:
    build:
      context: .
      dockerfile: grafana/Dockerfile
    container_name: grafana
    ports:
      - 9000:3000
    # If permament data needed uncomment below
    #volumes:
      #- grafana-data:/var/lib/grafana
    
#volumes:
  #grafana-data:
    #external: true